alldigitalrewards/rewardstack-sdk

.gitignore, src/Common/Entity/Domains.php, src/Common/Entity/Organization.php, src/Common/Entity/OrganizationReterive.php, src/Common/Entity/ProgramLayout.php, src/Common/Entity/ProgramList.php, src/Common/Entity/SingleSignOn.php, src/Common/Entity/SingleUserTransaction.php, src/Common/Entity/Transaction.php, src/Request/CreateAdjustmentRequest.php, src/Request/CreateOrganizationRequest.php, src/Request/CreateParticipantRequest.php, src/Request/OrganizationDomainsRequest.php, src/Request/OrganizationListRequest.php, src/Request/OrganizationReteriveRequest.php, src/Request/ParticipantRequest.php, src/Request/ProgramLayoutRequest.php, src/Request/ProgramListRequest.php, src/Response/AdjustmentResponse.php, src/Response/CreateOrganizationResponse.php, src/Response/CreateParticipantResponse.php, src/Response/CreateTransactionResponse.php, src/Response/OrganizationDomainsResponse.php, src/Response/OrganizationListResponse.php, src/Response/OrganizationReteriveResponse.php, src/Response/ProgramLayoutResponse.php, src/Response/ProgramListResponse.php
Includes Wrapper for Program API
Includes wrapper for Organisation API's
Missing Create Participant API's
=> Added Wrapper for Program and Organisation API

src/Adjustment/CreateAdjustmentRequest.php, tests/Request/CreateAdjustmentRequestTest.php
=> Added reference to Create Adjustment method

examples/bootstrap.php, examples/create_participant_adjustment.php, src/Adjustment/CreateAdjustmentRequest.php
This allows the adjustment creation to allow a description
=> DS 2654 - Adjustment description support

composer.json, tests/Request/AdjustmentRequestTest.php, tests/Request/CreateAdjustmentRequestTest.php, tests/Request/CreateOrganizationRequestTest.php, tests/Request/CreateParticipantRequestTest.php, tests/Request/CreateProgramRequestTest.php, tests/Request/CreateSweepstakesEntryRequestTest.php, tests/Request/CreateTransactionRequestTest.php, tests/Request/OrganizationDomainsRequestTest.php, tests/Request/OrganizationListRequestTest.php, tests/Request/OrganizationRequestTest.php, tests/Request/OrganizationRetrieveRequestTest.php, tests/Request/ParticipantCollectionRequestTest.php, tests/Request/ParticipantRequest.php, tests/Request/ParticipantRetrieveRequestTest.php, tests/Request/ProgramLayoutRequestTest.php, tests/Request/ProgramListRequestTest.php, tests/Request/ProgramRequestTest.php, tests/Request/ProgramRetrieveRequestTest.php, tests/Request/SingleUserTransactionRequestTest.php, tests/Request/SsoTokenRequestTest.php, tests/Request/TransactionRequestTest.php
Added support for PHP8.
I also tested this working on 7.4 and 7.3
A TON of the tests are failing...
=> KIA-334 - Add support for PHP8 to RewardSTACK SDK

examples/update_transaction_meta.php, src/Transaction/AddTransactionMetaRequest.php, src/Transaction/AddTransactionMetaResponse.php
https://jira.alldigitalrewards.com/browse/DS-2638
=> DS-2638 update transaction meta added

src/Program/ProgramLayoutRequest.php, src/Transaction/CreateTransactionRequest.php, tests/Request/CreateTransactionRequestTest.php, tests/Request/ProgramLayoutRequestTest.php
just fixing this even though i cannot use the sdk, program layout response doesnt not hydrate correctly, needs fixing
=> DS-2890-fix-queryparam add separately

src/Common/Entity/AbstractEntity.php, src/Common/Entity/Adjustment.php, src/Common/Entity/Domains.php, src/Common/Entity/Organization.php, src/Common/Entity/OrganizationRetrieve.php, src/Common/Entity/Participant.php, src/Common/Entity/ParticipantCollection.php, src/Common/Entity/Program.php, src/Common/Entity/ProgramLayout.php, src/Common/Entity/ProgramRetrieve.php, src/Common/Entity/SingleSignOn.php, src/Common/Entity/SingleUserTransaction.php, src/Common/Entity/Transaction.php
https://jira.alldigitalrewards.com/browse/DS-3139
=> DS-3139 add toarray and make properties protected

examples/create_participant.php, examples/create_participant_transaction.php, examples/update_participant.php, src/Participant/CreateParticipantRequest.php, src/Participant/ParticipantRequest.php, src/Traits/MetaValidationTrait.php, src/Transaction/AddTransactionMetaRequest.php, src/Transaction/CreateTransactionRequest.php
=> DS-3140 add meta validation trait on requests

src/Common/Entity/Adjustment.php
=> DS-3140-v2 add properties on adjustment

examples/update_participant.php, src/Participant/ParticipantPutRequest.php
=> DS-3140-participant-put allow for phone number on put participant

src/Common/Entity/Program.php
=> DS-3140-program-attribute collect ssn missing

examples/bootstrap.php, src/Transaction/CreateTransactionRequest.php
=> Ds 3140 transaction create

src/Auth/AuthProxy.php
=> DS-3140-extend-authproxy-token-get

src/Program/ProgramRetrieveRequest.php
https://jira.alldigitalrewards.com/browse/DS-3213
=> DS-3213 add lang param to program request

composer.json, composer.lock
https://jira.alldigitalrewards.com/browse/IPS-429
=> IPS-429-language-mapper allow min version 1

src/Participant/AddressRequest.php
https://jira.alldigitalrewards.com/browse/IPS-425
=> IPS-425 default to US if country not present

src/RedemptionApi/CampaignRetrieveByPinRequest.php
https://jira.alldigitalrewards.com/browse/IPS-429
=> IPS-429-fix-response on single campaign by pin

src/Common/Entity/ProgramContentResponse.php
https://jira.alldigitalrewards.com/browse/DS-3250
=> DS-3250 add language toggler property to content response

src/AVS/AddressValidationRequest.php
added lang querystring to the avs request
https://jira.alldigitalrewards.com/browse/DS-3572
No
No
No
Yes
Yes
=> DS-3572 - add lang querystring to avs request

src/Common/Entity/ProgramContentResponse.php
add show wallet view property on program content response
https://jira.alldigitalrewards.com/browse/DS-3543
No
No
No
Yes
Yes
=> DS-3543 add show wallet view property on program content response

examples/participant_list.php, src/Common/Entity/ParticipantCollection.php, src/Participant/ParticipantCollectionFilter.php
add status filter for participant list
https://jira.alldigitalrewards.com/browse/DS-3684
No
No
No
Yes
Yes
=> Ds 3684 v3

examples/participant_list.php, src/Common/Entity/ParticipantCollection.php
add language to participant response with mapper hydration
https://jira.alldigitalrewards.com/browse/DS-3684
No
No
No
Yes
Yes
=> Ds 3684 v5 add language to participant response with mapper hydration

examples/program_list.php, src/Common/Entity/ProgramRetrieve.php, src/Program/ProgramCollectionFilter.php, tests/Response/ProgramListResponseTest.php, tests/fixtures/program_list_response.json
add end date to program filter collection, and response
https://jira.alldigitalrewards.com/browse/DS-3790
No
Yes
Yes
Yes
Yes
=> DS-3790 add end date to program filter collection, and response

src/Common/Entity/Program.php
add end date to program retrieve response entity
https://jira.alldigitalrewards.com/browse/DS-3790
No
Yes
No
Yes
Yes
=> DS-3790-v2 add end date to program retrieve response entity

src/Transaction/CreateTransactionRequest.php, tests/Request/CreateTransactionRequestTest.php
add avs_disabled default false to create transaction
https://jira.alldigitalrewards.com/browse/DS-3807
No
Yes
No
Yes
Yes
=> DS-3807 add avs_disabled default false to create transaction

src/Common/Entity/Transaction.php
add products and source in Transaction list response
https://jira.alldigitalrewards.com/browse/DS-3867
No
Yes
No
Yes
Yes
=> DS-3867 add products and source in Transaction list response

src/Common/Entity/Transaction.php
add a source display in case we want to keep the original format
https://jira.alldigitalrewards.com/browse/DS-3867
No
Yes
No
Yes
Yes
=> DS-3867-v2 add a source display in case we want to keep the original format

src/Common/Entity/Transaction.php
Return empty string of source is null
https://jira.alldigitalrewards.com/browse/DS-3903
Yes
No
No
Yes
Yes
=> DS-3903 - return empty string if source isnt set

composer.json, composer.lock, tests/LanguageTest.php
Adds support for language mapper version 2 
https://jira.alldigitalrewards.com/browse/DS-3967?filter=10409
No
No
No
Yes
Yes
=> DS-3967 - add support for language mapper version 2

examples/get_participant_transaction_items.php, examples/get_participant_transactions.php, src/Common/AbstractCollectionFilter.php, src/Common/Entity/OrderBy.php, src/Transaction/TransactionItemCollectionFilter.php
new order by filter
https://jira.alldigitalrewards.com/browse/DS-4048
No
No
No
Yes
Yes
=> DS-4048 new order by filter

examples/get_participant_adjustments.php, src/Adjustment/AdjustmentCollectionFilter.php
add collection filter to allow for orderby on adjustments
https://jira.alldigitalrewards.com/browse/DS-4052
No
Yes
No
Yes
Yes
=> DS-4052 add collection filter to allow for orderby on adjustments

examples/create_program.php, examples/program.php, src/Common/Entity/Program.php, src/Common/Entity/ProgramRetrieve.php, src/Program/CreateProgramRequest.php, src/Program/ProgramRequest.php, tests/Request/CreateProgramRequestTest.php
add enable email login property to requests and response for Program
https://jira.alldigitalrewards.com/browse/DS-2115
No
Yes
Yes
Yes
Yes
=> Ds 2115 add enable email login property to requests and response for Program

examples/get_email_participant_auth.php, src/Participant/EmailParticipantAuthRequest.php
new endpoint for email participant auth
https://jira.alldigitalrewards.com/browse/DS-2115
No
Yes
No
Yes
Yes
=> DS-2115-v2 new endpoint for email participant auth

src/Transaction/CreateTransactionRequest.php
Update empty to isset for ranged amount on create transaction request entity
https://jira.alldigitalrewards.com/browse/DS-4222
No
No
No
Yes
Yes
=> DS-4222 - check for isset not empty on value for ranged product

examples/participant_password_recover_request.php, examples/participant_password_update_request.php, src/Common/Entity/AbstractEntity.php, src/Participant/ParticipantPasswordResetRequest.php, src/Participant/ParticipantPasswordUpdateRequest.php
add password recovery requests
https://jira.alldigitalrewards.com/browse/DS-4207
No
No
No
Yes
Yes
=> DS-4207 add password recovery requests

src/Auth/JwtToken.php
DS-4353 - reduce comparison time on token expiration to make up for differences in server time sync.
https://jira.alldigitalrewards.com/browse/DS-4353
No
No
No
Yes
Yes
=> DS-4353 - reduce comparison time on token expiration to make up for differences in server time sync.
